# Generated by Django 3.2.5 on 2021-11-15 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e9cc0b9-9634-4559-b0d2-5ef1c1319178'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
